workspace = "oasis"
version = 1

[library.oasis_core]
dir = "src"
modules = ["string_util", "fs", "process", "toolchain", "manifest", "layout", "builder", "cleaner", "bootstrap"]
packages = ["unix"]

[executable.oasis]
dir = "src"
main = "main"
modules = ["tester", "cli"]
deps = ["oasis_core"]

[test.test_runner]
dir = "test"
main = "test_main"
modules = ["test_support", "test_manifest", "test_layout", "test_build", "test_clean", "test_process", "test_run", "test_test", "test_toolchain", "test_bootstrap"]
deps = ["oasis_core"]
