# Generated by scripts/render_bootstrap_mod_use.ml --format seed-metadata.
# Refresh with: make refresh-bootstrap-seed-metadata
BOOTSTRAP_LIBRARY_COMPILE_SOURCES := src/string_util.ml src/fs.ml src/process.ml src/toolchain.ml src/manifest.ml src/explain.ml src/layout.ml src/builder.ml src/cleaner.ml src/installer.ml src/deps.ml src/env_report.ml src/graph.ml src/migrate.ml src/repl.ml src/bootstrap.ml src/bench.ml
BOOTSTRAP_LIBRARY_MODULE_STEMS := string_util fs process toolchain manifest explain layout builder cleaner installer deps env_report graph migrate repl bootstrap bench
BOOTSTRAP_LIBRARY_PACKAGES := unix
